//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exit
    {
        public int Id { get; set; }
        public int To { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Room Room { get; set; }
    }
}
