//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMud
{
    public partial class Mob
    {
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Player Player { get; set; }
    }
}
