//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SharpMud
{
    public partial class MudDataContainer : DbContext
    {
        public MudDataContainer()
            : base("name=MudDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Mob> Mobs { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Exit> Exits { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Direction> Directions { get; set; }
    }
}
